---
- name: Converge
  hosts: all
  roles:
    - role: wazuh/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: "manager-{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}"
        port: 1514
        protocol: udp
        api_port: 55000
        api_proto: 'http'
        api_user: ansible
    wazuh_agent_authd:
      registration_address: "manager-{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}"
      enable: true
      port: 1515
      ssl_agent_ca: null
      ssl_auto_negotiate: 'no'
