- hosts: apache
  tasks:
  - name: Install apache block
    block:
      - name: Install apache server in Linux systems
        become: yes
        become_user: root
        import_role: 
          name: ../roles/apache
        when: ansible_os_family == "Debian" or ansible_os_family == "RedHat" or ansible_os_family == "Solaris"
      - name: Install apache server in Windows and macOS hosts
        import_role: 
          name: ../roles/apache
        when: ansible_os_family == "Windows" or ansible_os_family == "Darwin"
