# https://archive.apache.org/dist/httpd/binaries/win32/?C=M;O=D openssl msi with its sha file
# https://www.apachelounge.com/download/VS16/binaries binaries and checksums
service: httpd
apache_version: 2.4.54
home_dir: C:\Users/qa
# latest stable version
apache_zip_url: "https://www.apachelounge.com/download/VS16/binaries/httpd-2.4.54-win64-VS16.zip"
apache_algorithm: sha256 
apache_checksum: b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
apache_zip_file: httpd-{{apache_version}}-win64-VS16.zip
apache_zip_path: "{{home_dir}}/{{apache_zip_file}}"
apache_folder_path: "{{home_dir}}/Apache24"
apache_bin_path: "{{apache_folder_path}}/bin/httpd.exe"
