- name: Install apache server
  package:
    name: "{{ program }}"
    state: present

- name: "Start {{ service }} service"
  service:
    name: "{{ service }}"
    state: started

- name: "Check {{ service }} is running"
  command: systemctl status "{{ service }}"
  register: service_status
  failed_when: (service_status.stderr | length > 0) or ("active (running)" not in service_status.stdout )
