- name: Install CSWpkgutil
  become: true
  shell: pkgadd -d http://get.opencsw.org/now -n

- name: Fetch new catalog and descriptions
  become: true
  shell: /opt/csw/bin/pkgutil -U 

- name: Install apache2
  become: true
  shell: /opt/csw/bin/pkgutil -y -i apache2

- name: List files
  become: true
  shell: /usr/sbin/pkgchk -L CSWapache2

- name: Enable service
  become: true
  shell: svcadm -v enable /network/http:apache2
