- name: Download the Apache binaries
  win_get_url:
    url: "{{ apache_zip_url }}"
    dest: "{{ home_dir }}"
    checksum: "{{apache_algorithm}}:{{apache_checksum}}"

- name: Unzip Apache binaries zip
  community.windows.win_unzip:
    src: "{{ apache_zip_path }}"
    dest: "{{ home_dir }}"
    creates: "{{ apache_folder_path }}"

- name: Replace Apache's ServerRoot location
  community.windows.win_lineinfile:
    path: "{{ apache_folder_path }}/conf/httpd.conf"
    backrefs: yes
    regex: Define SRVROOT "c:/Apache24"
    line: Define SRVROOT "c:/Users/qa/Apache24"

- name: Verify httpd.conf
  ansible.windows.win_shell: "{{ apache_bin_path }} -t"

- name: Install Apache service
  ansible.windows.win_shell: "{{ apache_bin_path }} -k install"

- name: Start Apache service
  ansible.windows.win_shell: "{{ apache_bin_path }} -k start"
