wazuh_repo:
  apt: 'deb https://packages-dev.wazuh.com/4.x/apt/ stable main'
  yum: 'https://packages-dev.wazuh.com/4.x/yum/'
  gpg: 'https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH'
  key_id: '0DCFCA5547B19D2A6099506096B3EE5F29111145'

certs_gen_tool_version: "{{ CERTS_GEN_TOOL_VERSION }}"

# Url of certificates generator tool
certs_gen_tool_url: "https://packages-dev.wazuh.com/{{ certs_gen_tool_version }}/wazuh-certs-tool.sh"
