---
- name: Creating inventory using templates
  hosts: localhost

  tasks:
  - name: "Template a file"
    ansible.builtin.template:
      src: "{{ source_template }}"
      dest: "{{ dest_inventory}}"
