---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      ignore: .virtualenv
platforms:
  - name: kibana-${MOL_PLATFORM:-centos7}
    image: ${MOL_IMAGE:-milcom/centos7-systemd}
    command: /sbin/init
    ulimits:
      - nofile:262144:262144
    privileged: true
    memory_reservation: 1024m
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  playbooks:
    docker:
      create: ../default/create.yml
      destroy: ../default/destroy.yml
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  lint:
    name: ansible-lint
    enabled: true
  inventory:
    group_vars:
      all:
        elasticsearch_jvm_xms: 256
verifier:
  name: testinfra
  lint:
    name: flake8
