version: 1
formatters:
  simple:
    format: '[%(asctime)s] [%(levelname)s] [%(process)d] [%(threadName)s] [%(name)s]: %(message)s'
  colored:
    (): colorlog.ColoredFormatter
    format: '%(log_color)s[%(asctime)s] [%(levelname)s] [%(process)d] [%(threadName)s] [%(name)s]: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
    log_colors:
      DEBUG:    cyan
      INFO:     green
      WARNING:  yellow
      ERROR:    red
      CRITICAL: red,bg_white
handlers:
  console:
    class: colorlog.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: /tmp/flowbacca.log
root:
  level: DEBUG
  handlers: [console, file]
