Project path: "../../tests/integration"

Output path: "wazuh_testing/qa_docs/output"

Include paths:
  - "../../tests/integration/test_wazuh_db"
  - "../../tests/integration/test_vulnerability_detector"
  - "../../tests/integration/test_remoted"
  - "../../tests/integration/test_agentd"

Include regex:
  - "^test_.*py$"

Group files:
  - "README.md"

Function regex:
  - "^test_"

Ignore paths:
  - "../../tests/integration/test_wazuh_db/data"

Output fields:
  Module:
    Mandatory:
      - brief
      - category
      - modules
      - daemons
      - component
      - os_platform
      - os_vendor
      - os_version
      - tiers
    Optional:
      - tags
  Test:
    Mandatory:
      - description
      - wazuh_min_version
      - parameters
      - behaviour
      - expected_behaviour
    Optional:
      - status 

Test cases field: test_cases

Module info:
  - test_system: os_platform
  - test_vendor: os_vendor
  - test_version: os_version
  - test_target: component

Test info:
  - test_wazuh_min_version: wazuh_min_version