name: Changelog
on:
  pull_request:
    branches:
      - master
      - '[0-9]+.[0-9]+'
jobs:
  Update:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-20.04
    steps:
      - name: Get the updated files
        id: updated_files
        uses: jitterbit/get-changed-files@v1
        with:
          format: csv

      - name: Save the updated files data
        run: echo ${{ steps.updated_files.outputs.added_modified }} > updated_files.txt

      - name: Check if changelog file has been updated
        run: egrep -i CHANGELOG.md updated_files.txt || (echo "Changelog file has not been updated" && exit 1)
