name: Code analysis
on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize
jobs:
  Linting:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-20.04
    steps:
      - name: Download files
        uses: actions/checkout@v3

      - name: Install pycodestyle and yamllint linter
        run: python -m pip install pycodestyle==2.8.0 yamllint==1.26.3 flake8==6.0.0

      - name: Get the updated files
        id: updated_files
        uses: Ana06/get-changed-files@v2.1.0
        with:
          format: csv

      - name: Save the updated files data
        run: echo ${{ steps.updated_files.outputs.added_modified }} > updated_files.txt

      - name: Run linter script
        run: |
          chmod +x .github/workflows/scripts/linter.py
          python .github/workflows/scripts/linter.py --file updated_files.txt -c .github/workflows/scripts/config
